apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: web-terminal
spec:
  source:
    repoURL: https://github.com/buuhsmead/cluster-config.git
    targetRevision: HEAD
    path: overlays/default/components/web-terminal
