apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - subscription.yaml
  - https://github.com/redhat-cop/gitops-catalog/web-terminal-operator/operator/overlays/fast?ref=main

